# Generated by Django 3.0.4 on 2020-03-09 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_obce', models.CharField(max_length=40, verbose_name='Název obce')),
            ],
        ),
        migrations.CreateModel(
            name='Tym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=40, verbose_name='Název týmu')),
                ('informace', models.TextField(verbose_name='Informace o týmu')),
                ('znak', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Znak týmu')),
                ('obec', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fotbal.Obec')),
            ],
        ),
        migrations.CreateModel(
            name='Zapasy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skore_domaci', models.IntegerField(max_length=2, verbose_name='Skóre domácích')),
                ('skore_hoste', models.IntegerField(max_length=2, verbose_name='Skóre hostů')),
                ('datum', models.DateField(verbose_name='Datum zápasu')),
                ('cas', models.TimeField(verbose_name='Čas zápasu')),
                ('domaci', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='domaci', to='fotbal.Tym')),
                ('hoste', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hoste', to='fotbal.Tym')),
            ],
        ),
        migrations.CreateModel(
            name='Realizacni_tym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=20, verbose_name='Jméno')),
                ('prijmeni', models.CharField(max_length=30, verbose_name='Příjmení')),
                ('narozeni', models.DateField(verbose_name='Datum narození')),
                ('pozice', models.CharField(max_length=25, verbose_name='Pozice')),
                ('tym_nazev', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fotbal.Tym')),
            ],
        ),
        migrations.CreateModel(
            name='Hrac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=20, verbose_name='Jméno')),
                ('prijmeni', models.CharField(max_length=30, verbose_name='Příjmení')),
                ('narozeni', models.DateField(verbose_name='Datum narození')),
                ('post', models.CharField(blank=True, max_length=20, null=True, verbose_name='Post hráče')),
                ('cislo_dresu', models.IntegerField(max_length=2, verbose_name='Číslo dresu')),
                ('tym_nazev', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fotbal.Tym')),
            ],
        ),
    ]
